name: Deploy

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        services:
          regis:
            image: redis
            ports:
              - 6379:6379

        steps:
            - name: Install redis cli
              run: sudo apt-get update -y && sudo apt-get install redis-tools -y

            - name: Test redis
              run: redis-cli -h localhost -p 6379 ping 

            - name: Print variable
              run: echo "${{ secrets.TOKEN_SECRECT }}"
            
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Instalar dependencias
              run: npm install
            
            - name: Correr pruebas
              run: npm run test
            
            - name: Construir pagina
              run: npm run build
            
            - name: Subir artefacto
              uses: actions/upload-pages-artifact@v3
              with:
                path: public/ 

    deploy:
      if: ${{ always() }}
      needs: build
      runs-on: ubuntu-latest

      permissions:
        pages: write
        id-token: write

      environment:
        name: github-pages
        url: ${{ steps.deployment-pages.outputs.page_url }}

      steps:
        - name: Deploy
          id: deployment-pages
          uses: actions/deploy-pages@v4